title: Michael Berthold
description: Personal website and portfolio
baseurl: ""
url: "https://michael-berthold.github.io"
theme: jekyll-theme-minimal

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  posts:
    output: true
    permalink: /musings/:year/:month/:day/:title/
